### PR TITLE
remove pytest-pep8 and replace with pep8

### PR DESCRIPTION
**Pull request by matsuuran**
addresses #650 

//cc @henn @shwsun @zenhack

### CODE REVIEW

**Comment by zenhack** [comment]
This looks reasonable to me, but I want to actually run it before signing off, and right now I'm on my phone. Will check back later

**Comment by shwsun** [comment]
Looks good, and it works fine on my environment.
+1

**Comment by zenhack** [comment]
We don't seem to be running this from travis; could you add a call for that to `.travis.yaml`?

**Comment by zenhack** [comment]
Looks good to me, +1. @shwsun, since there has been another commit pushed, I'll wait for you to confirm your +1 before merging.

**Comment by shwsun** [comment]
I am happy with it. +1

**Comment by zenhack** [comment]
Great, merging.

**Pull request merged**
