### PR TITLE
Use Correct SQL Alchemy methods

### LINKED ISSUE #308: Use correct SQLAlchemy methods
We should be using .one(), .count() or .exists() in many cases where we are just using .first() for DB queries.

### PR DESCRIPTION
**Pull request by naved001**
* Closes #308 

Please see my [comment here](https://github.com/CCI-MOC/hil/issues/308#issuecomment-327642054) to see what I did here and why.

### CODE REVIEW

**Comment by zenhack** [comment]
I'm not sure whether I agree with the count() -> first() change; we're also not interested in the contents of the tuple. What we really want is exists; was there a reason not to do that?

**Comment by naved001** [comment]
> I'm not sure whether I agree with the count() -> first() change; we're also not interested in the contents of the tuple.

Let's say there were 10,726 matches (highly unlikely obviously), then count would take some time but first() would just return on the first match (worst case would be returning a `None`). I know this is a very unlikely scenario with little to no performance benefits, but that was my reasoning.

> What we really want is exists; was there a reason not to do that?

I couldn't find it in the docs. Let me dig around more and I'll use that.

**Comment by naved001** [comment]
`exists()` seems needlessly complicated to me honestly. It makes the code less readable. 
I am wondering if I should even change it [here](https://github.com/CCI-MOC/hil/blob/master/hil/ext/network_allocators/vlan_pool.py#L57)

**Comment by zenhack** [comment]
I actually think I agree with you re: exists; maybe just revert that commit. 

Re: the vlan thing, I think leave it as is.

**Comment by naved001** [comment]
> I actually think I agree with you re: exists; maybe just revert that commit.

done.

**Comment by naved001** [comment]
@knikolla @shwsun @Izhmash can either of you review this? Thanks!

**Comment by naved001** [comment]
@SahilTikale want to review this? it's a small PR.

**Comment by naved001** [comment]
Thanks @shwsun for looking at it! :)

**Pull request merged**
