### PR TITLE
Update dbinit for latest APIs

### PR DESCRIPTION
**Pull request by henn**
I think we just need one reviewer for this, since it's not part of the main codebase.

### CODE REVIEW

**Comment by henn** [comment]
Actually, now that I am hooking dbinit.py into the CI testing, this should probably have the regular review process.

The reason for hooking it is that it would be good to have a script that devs can run to populate some objects into their HIL instance that's always ready to go.

@SahilTikale - you're welcome for adding more to the testing :-)

Also - please send any comments of cli.py or scripts/haas to #642. I included them into here because the integration tests don't do anything without the CLI commands returning an appropriate status code. I can take those out if reviewers would prefer.

**Comment by zenhack** [comment]
Two things:

1. re: #642, once that's merged, if you rebase the extra diffs should go away.
2. I like the idea of running example scripts with travis where possible, but I feel like it should be called out a little more explicitly as testing the *examples*, rather than the server.

**Comment by gsilvis** [comment]
Why is #642 merged into this at all?  As far as I can tell, the changes are independent

**Comment by gsilvis** [comment]
A little late, but, I finally noticed why you included #642 in this.

**Comment by gsilvis** [comment]
This has to be redone now...

**Comment by gsilvis** [comment]
Replaced by #664

**Pull request closed without merging**
