### PR TITLE
DB Migration Integer to BigInteger

### PR DESCRIPTION
**Pull request by Izhmash**
* In response to issue #315:
* I've updated the database creation source so that every primary key is a BIGINT rather than an INTEGER.
* 3 migration scripts: one for haas, one for haas.ext.obm.mock, and one for haas.ext.switches.mock.
* Type changes in the DB are now noticed by Alembic through env.py.
* Note: overflow test implementation is in progress

### CODE REVIEW

**Comment by zenhack** [comment]
*sigh* it looks like the client tests are acting up again

It's unfortuante that we don't actually get the errors back when travis just times out...

//cc @henn, @SahilTikale

**Comment by naved001** [comment]
The tests failures here are a bit weird as almost all tests are failing this time. Running it locally, the tests are erroring (E) instead of failing (F) saying `socket.error: [Errno 98] Address already in use
`

I was also wondering why doesn't alembic just generate pep8 formatted commands/scripts

**Comment by Izhmash** [comment]
Since more development will be necessary for this, I'm going to work on getting one table migrated without error first, then make another PR when I'm certain that the rest of the tables can be updated without error.

**Comment by Izhmash** [comment]
After some research on various forums, it's looking like sqlite does not support BIGINT primary keys.  However, the default integer in sqlite can be as large as 8 bytes.  Postgres, on the other hand, does accept a BIGINT primary key.

Someone has an example [here](https://stackoverflow.com/questions/18835740/does-bigint-auto-increment-work-for-sqlalchemy-with-sqlite) about having the code behave differently depending on the database used.  Should I go down that route, or is the extra complexity to the code not worth it?

**Comment by Izhmash** [comment]
I'd argue for the postgres BIGINT migration and having sqlite make up for it some other way since sqlite is not used in production.

**Comment by zenhack** [comment]
We can probably lean on sqlalchemy to paper over the differences; might have to dig through the docs a bit, but I'm willing to bet there is a way to get it to use different types for different dbs.

**Comment by Izhmash** [comment]
Just for an update, I've been working on this on a private branch. I've got a solution that works when upgrading just the NIC table.  Going to push it here as soon as the migration.py tests stop failing.

**Comment by Izhmash** [comment]
I'm going to close this and open a new pull request with my other branch.

**Pull request closed without merging**
