### PR TITLE
Fix: Typo in the docs string. 

### PR DESCRIPTION
**Pull request by xuhang57**
Simple fix.

### CODE REVIEW

**Comment by zenhack** [comment]
Huh, not sure why the tests are failing. looks to be a problem importing the postgres backend for sqlalchemy, but nothing's changed on our end...

**Comment by xuhang57** [comment]
Not sure either. Just restarted the build.

**Comment by zenhack** [comment]
This seems to have failed again, and we got the same thing when @henn updated #803. We didn't change anything; maybe some dependency shifted underneath us?

**Comment by zenhack** [comment]
Yeah, travis updated their image: https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by xuhang57** [comment]
Right, that's why it is failing. Maybe change the CI to use the previous version of Ubuntu14? Or, wait for a fix.

**Comment by naved001** [comment]
@xuhang57 #805 fixes this. Once that is merged, you can just rebase this PR on top of master and it should pass.

**Comment by zenhack** [comment]
+1, merging.

**Pull request merged**
