### PR TITLE
Load haas config

### PR DESCRIPTION
**Pull request by matsuuran**
Issue #337 

This will load the haas.cfg from different locations in this order:

1. Current directory `haas.cfg` or the filename passed into the function
2. `~/.haas.cfg`
3. `/etc/haas.cfg`

They are in reverse order in the `load()` function because each subsequent overrides the previous.  I left the filename as a pass in because it gives a little more flexibility and if we wanted to add a way to pass in a filename from the command line (as @zenhack mentioned in #337) in the future it is there.  Obviously I can take it out if anyone has any real issue.

### CODE REVIEW

**Comment by zenhack** [comment]
The behavior of configparser is to actually *merge* the files, so it won't delete options that were there in configs it loaded first. This is probably not what we want, particularly with the way extensions work.

The `read` method returns the list of successfully loaded files, so you could also do:

```python

if cfg.read(filename) != []:
     return

```

with similar clauses for the other locations.

Also, need to update the docs re: new behavior.

**Comment by shwsun** [comment]
@matsuuran @zenhack 
We have discussed this one during today's hil meeting. The issue existed a long time ago, and from our perspective, loading haas config from different locations will only benefit the developers. Right now we already have the ``HAAS_ENDPOINT`` variable and the haas.cfg location should no longer be an issue.

**Comment by zenhack** [comment]
I'm fine with whatever folks want to do with this; if that just means closing it, go for it.

**Comment by knikolla** [comment]
Closed as requested.

**Pull request closed without merging**
