### PR TITLE
revert_port

### PR DESCRIPTION
**Pull request by kylehogan**
addresses issue #508 

- [ ] call to remove all vlan access
- [x] show port call
- [x] revert_port can reinstate network attachments that were present in haas database
- [ ] test the case where there are multiple network attachments

### CODE REVIEW

**Comment by kylehogan** [comment]
@ron-unrau 
my show_switch can be seen in the api here. I also have a few unit tests for it. Can you let me know if you decide to use any of it and I can then review it in your pull request and remove it from here? Thanks!

**Comment by ron-unrau** [comment]
The basic framework of my implementation is exactly the same as yours, the
only difference is that I was going to return the information provided in
switch_register, while yours is returning the info from
switch_register_port.

I don't speak github yet, but in my world we would have said: since your
review is pretty much done, you may as well push your changes to the
mainline, and then I can pull them into my branch and add the extra fields.
(Did that make any sense to you?)

I don't think anyone is really waiting for the stuff in my show_switch
implementation, and besides, I have no idea how to handle the polymorphism
yet anyway. In summary, I think it's fine if my changes wait for a week.

< ron

**Comment by kylehogan** [comment]
This pull request is blocked until it can get tested in a development environment because of the revert_port functionality so nothing in here will get merged soon. Because of that it may be better to keep show_port as your separate pull request.

**Comment by matsuuran** [comment]
@kylehogan @ron-unrau 
just wanted to see if this would be able to be tested on the server @SahilTikale is setting up

**Comment by shwsun** [comment]
I have tested the functions included in devhaas, but it looks like some of them are broken.

I fixed the schema before that. If there are no PR regarding any functions related then I guess I have to fix broken ones by myself.

**Comment by matsuuran** [comment]
@shwsun just wanted to see how this was going

**Comment by shwsun** [comment]
@matsuuran I guess we should close this one and I will reference it in my PR.

**Comment by matsuuran** [comment]
@henn @SahilTikale @gsilvis can you close this? there is another PR open for this #621

**Comment by henn** [comment]
Done!

**Pull request closed without merging**
