### PR TITLE
Upgrade Flask from 0.10.1 -> 0.11.1 -> 0.12.1

### PR DESCRIPTION
**Pull request by xuhang57**
Currently, the most stable release is 0.12. (http://flask.pocoo.org/docs/0.12/changelog/)

And not sure whether we should jump to 0.12 or we should go from 0.10 -> 0.11 ->0.12

Relates: https://github.com/CCI-MOC/hil/issues/975

### CODE REVIEW

**Comment by naved001** [comment]
it's odd that the obmd migration tests are failing :/

**Comment by zenhack** [comment]
I suspect the test failures are due to the change in https://github.com/CCI-MOC/obmd/pull/10; we need to add the DB info to the config file we're generating there.

I'd say let's upgrade straight to 0.12.

**Comment by xuhang57** [comment]
Coverage is decreased because we never test the `setup.py` file? 

I don't have the hil `pypi` creds but should we add a test for testing `pip install hil`?
Not sure whether adding this in `travis` would make more sense?

**Comment by xuhang57** [comment]
The coveralls actually shows there is no change in coverage percentage. However, the check fails here on GitHub. I will restart the build and see whether it fixes.

**Pull request merged**
