### PR TITLE
Create a specs directory/template

### PR DESCRIPTION
**Pull request by henn**
I tried to incorporate some of the feedback from #783 and our meeting.

### CODE REVIEW

**Comment by henn** [comment]
Please note that because this is mostly independent, it doesn't need to be merged before the great name change.

CC @SahilTikale @naved001 @zenhack @pjd-nu @knikolla

**Comment by zenhack** [comment]
Since this is the last open pr and isn't going to have nasty merge conflicts, I'm going to go ahead and do the rename; expect a pr soone.

**Comment by henn** [comment]
@zenhack - did you see this part?

> Bug fixes/minor features do not require a spec, and should be submitted directly as a PR.

**Comment by zenhack** [comment]
@henn, I did. I still think it's a bit too strong; I'd prefer something along the lines of "the use of specs is descretionary; most features will involve some discussion on the bug tracker; if a spec seems warranted, someone may propose it."

I'm not willing to accept a stronger recommendation than that; I still kinda think this is a bit pointless, and don't want to endorse process we don't need.

**Comment by henn** [comment]
I think requiring a short writeup for major design changes would be good, if not for the ability to debate it then for the documentation and prevention of throwaway work.

How do others feel?
@okrieg @pjd-nu @SahilTikale

**Comment by henn** [comment]
@zenhack - I thought about this some more and realized that it made sense there there could be discussion documented in a PR/issue elsewhere. Let me know what you think of the revised version.

**Comment by SahilTikale** [comment]
@zenhack will soon respond to this with his reviews.

**Pull request merged**
