### PR TITLE
Replace lambdas

### PR DESCRIPTION
**Pull request by Izhmash**
* In response to issue #768 
* Error-checking lambda functions in haas/cli.py removed.
* `check_clientlib_response()` functionality & error checking implemented in main

### CODE REVIEW

**Comment by zenhack** [comment]
Can you explain to me why you re-added the definition of `check_clientlib_response`?

Also, on #768, we talked about descriminating based on error type. I realize now it's not doing that in the first place, but I'd like to distinguish between `FailedAPIException` and other, unexpected errors -- mind adding another `except` case (and maybe change the `Exception` one to print "unexpected error" or something)?

**Comment by Izhmash** [comment]
@zenhack check_clientlib_respsonse is now removed again, re-adding it was a mistake.

For the exceptions, right now there is one for `FailedAPICallException`, `InvalidAPIArgumentsException`, and now unexpected errors.  Was there a fourth `except` that I should add?

**Comment by zenhack** [comment]
No, I don't think there were other cases. One other thing that I noticed though: right now we're just doing a sys.exit(number) for the two specific cases, without printing any specific error info -- it would be better to still print the basic information from the error in these cases as well, as we currently do on master.

**Comment by Izhmash** [comment]
Now it should print error information rather than just the numbers.

**Comment by zenhack** [comment]
Should probably delete the mis-typed call that you're fixing in #799, as well. Other than that this looks good to me.

**Comment by Izhmash** [comment]
I think everything is all set now.  Also closed #799.

**Comment by zenhack** [comment]
@naved001, would you give this a second review?

**Pull request merged**
