### PR TITLE
Revert "adding tpm metadata for nodes"

### PR DESCRIPTION
**Pull request by zenhack**
Reverts CCI-MOC/hil#680

See the discussion there; this broke our CI, so I'd like to back it out and ask @kylehogan to fix the problems before we merge it again.

//cc @henn, @shwsun, @knikolla

### CODE REVIEW

**Comment by kylehogan** [comment]
What do I need to do to fix this? My understanding is that this pull request will revert to before mine was merged (if so, +1) and then I will need to merge master into my branch and fix the errors

**Comment by kylehogan** [comment]
actually after looking at it it might just be the import statements for Ipmi in the unit test for model.py. The two failing tests say that Ipmi is not defined and the only thing that seems to have changed is the location of the import statement.

**Comment by zenhack** [comment]
Yeah, those got removed as part of #698; should be pretty trivial to fix.

**Comment by kylehogan** [comment]
So do we want to revert it then make the changes or should I make a new PR with the fix? I'm not sure which way is standard

**Comment by zenhack** [comment]
I don't think we have a standard; I figured it would be good to have master not broken asap, but if you can get a fix out quickly we can just merge that.

**Comment by henn** [comment]
Thanks for posting this!

I'd say that if Kyle can fix this by mid-day tomorrow, then that would be preferable over reverting this and causing merge confusion. If not, then I'll merge this tomorrow.

**Comment by zenhack** [comment]
Quoting Jason Hennessey (2017-01-26 18:18:40)

>    Thanks for posting this!
>
>    I'd say that if Kyle can fix this by mid-day tomorrow, then that would
>    be preferable over reverting this and causing merge confusion. If not,
>    then I'll merge this tomorrow.

Sounds good.

**Comment by kylehogan** [comment]
@henn @zenhack there's a fix PR now! #712 
it was really trivial - one missing import statement.

**Comment by zenhack** [comment]
Commented. I'm going to close this, since it seems like it will be unnecessary.

**Pull request closed without merging**
