### PR TITLE
Document haas.ext.auth.null extension in example config

### PR DESCRIPTION
**Pull request by henn**

### CODE REVIEW

**Comment by kamfonik** [comment]
do you think an example database endpoint would be useful?

**Comment by henn** [comment]
@kamfonik - we currently have examples for sqlite and postgres. Was there a particular example you were thinking of?

**Comment by kamfonik** [comment]
@henn whoops, missed the fact that the examples were above, I was looking near the auth database setting in the diff.

Looks good +1

**Comment by henn** [comment]
Given that this is akin to documentation, I am merging this with one approval.

**Pull request merged**
