### PR TITLE
Mass Open Cloud administrative updates

### PR DESCRIPTION
**Pull request by xuhang57**
- [x] Docs changes from Massachusetts Open Cloud -> Mass Open Cloud

- [x] Extend the date from 2012, 2013, 2014, 2015, 2016, 2017 to 2018

- [x] Clean up the legal statement on each individual file and having a COPYING statement up-to-date.

This PR solves: https://github.com/CCI-MOC/hil/issues/933

### CODE REVIEW

**Comment by xuhang57** [comment]
@naved001  just want to make sure I am on the right track.

**Comment by xuhang57** [comment]
@zenhack what's your opinion on the copyright headers in those individual files? I mean, since I am cleaning up them anyways, should we get rid of them and have only one `COPYING` file in the repo? So we don't have to change the date on all files one by one. Thoughts?

**Comment by zenhack** [comment]
I'm fine just deleting them -- I can never be bothered to remember to update them, and clearly neither can anyone else. As long as it's in COPYING it's good enough for me.

**Comment by naved001** [comment]
Yeah, I agree with Ian. Let's just get rid of the redundant stuff.

**Comment by xuhang57** [comment]
@zenhack @naved001 please take a look whenever you have time.

**Comment by naved001** [comment]
Yep, I'll get back to all HIL stuff tomorrow by latest. Need to set somethings up at MGHPCC.

**Pull request merged**
