### PR TITLE
Use github mirror instead of git.o.o

### PR DESCRIPTION
**Pull request by jeremyfreudberg**
Just a test... not in the mood to learn how to run Travis without making a PR

### CODE REVIEW

**Comment by Izhmash** [comment]
For future reference if this ever breaks, `pip install -U requests[security]` also fixes the certificate issue.

**Comment by Izhmash** [comment]
Note: this fixes the current Travis certificate error.

**Comment by zenhack** [comment]
What does the `[securty]` extra actually contain? If the problem is a software support thing on our end, just specifying that in our config might be a better solution.

**Comment by Izhmash** [comment]
@zenhack  I'm not sure exactly what that contains, but in a quick test I found it also works.  @jeremyfreudberg 's solution works fine though since it doesn't require any more installing.

**Comment by jeremyfreudberg** [comment]
@zenhack `[security]` adds a few extra packages, see here: https://github.com/requests/requests/blob/master/setup.py#L99

the solution that i have provided here would be prioritizing speed

**Comment by zenhack** [comment]
Ok. Could you add a comment mentioning why we're pulling from github? Should document the fact that this is purposeful, rather than just an arbitrary choice.

**Comment by naved001** [comment]
@zenhack there's a comment now, you can merge this if you are satisfied.

**Comment by zenhack** [comment]
Works for me, merged.

**Pull request merged**
