### PR TITLE
Define auth behavior for Project 'None'

### PR DESCRIPTION
**Pull request by henn**
Fall back to have_admin()

Appreciate any suggestions for ways to test. This is needed before #554.

@zenhack - would appreciate your input.

### CODE REVIEW

**Comment by zenhack** [comment]
I don't follow; why is this needed for #554?

This seems questionable to me; I don't see any good reason for us to be passing `None` to this at all.

**Comment by henn** [comment]
The code in #554 currently has cases where it passes `None` to the auth calls for networks owned by the admin (which we represent using `owner = None`).

The alternative is to change those uses and stick an `assert project is not None` in the auth code.

Either way, we should define the behavior one way or the other in case this happens again.

**Comment by zenhack** [comment]
My preference would be to check in the client code. In general, when desiging APIs I think desiging for the call site is a good idea; it won't be obvious from looking at the client code that it's not just doing something dangerous/wrong, unless you actually go read the docstring for that function.

I think adding an assert is a good idea, and I'd actually suggest `assert isinstance(project, model.Project)`; I've seen a few slip-ups (not that have been merged, to my knowledge) where people have passed in the name of the project, instead of the project model. This would cover both cases.

**Comment by shwsun** [comment]
IMO, either way would be fine. If we want to use this ``None`` term as a default behavior of HIL, then probably do the ``assert`` at the beginning would be better.

However, I do thhink this Project ``None`` needs to be a little more clear in the doc.

**Comment by henn** [comment]
> My preference would be to check in the client code

I think adding the assert and doing the check in the client code is probably more internally consistent, since in one case (for `owner`) `None` means _admin-only_, and in the other (for `access`) is means _everyone_.

Closing this in favor of what we discussed above.

**Pull request closed without merging**
