### PR TITLE
Fix typo in psql docs

### PR DESCRIPTION
**Pull request by Izhmash**
Fixes a small typo to match up instructions and commands.

### CODE REVIEW

**Comment by naved001** [comment]
On a slightly unrelated note, I think our installation docs are a tad bit confusing to follow. Sometimes even I get tired of doing all that, which is why I wrote some helper scripts which can be found here https://github.com/CCI-MOC/admin-tools/tree/master/hil_installation

In the long term I want to do that using Ansible.

**Comment by Izhmash** [comment]
@naved001  I saw that, that definitely helps too.

**Comment by zenhack** [comment]
LGTM, merging.

**Comment by zenhack** [comment]
@naved001, re: the installation docs in general, while in production you definitely want to be automating things, I very much think it's important to keep "manual" installation within the grasp of mere mortals. If this was ever a property openstack had, it was lost before the MOC even existed, and when the docs were first written, George and I were both pretty adamant about not letting that happen to HIL as well. So I'm all for helping folks automate setup, but I want to be careful to avoid letting the automation mask a process that's fundamentally too complex.

**Comment by naved001** [comment]
>  I very much think it's important to keep "manual" installation within the grasp of mere mortals.

I completely agree with you on this. I might rewrite some part of the docs that I think can be improved.

**Pull request merged**
