### PR TITLE
keystoneauth1 lib imported in cli.py

### PR DESCRIPTION
**Pull request by Izhmash**
I needed to add these imports so that the keystone code could run correctly.  Python was reporting previously that `v3` was undefined.  More info here: https://docs.openstack.org/python-keystoneclient/latest/using-sessions.html

### CODE REVIEW

**Comment by jeremyfreudberg** [comment]
Related commit (don't ask how I found this): https://github.com/SahilTikale/hil/commit/485ced3d75edb22491d397ef822120dc5d008bdf#diff-f91b561bea80fef80859e07202890ee0

**Comment by SahilTikale** [comment]
makes sense. +1

**Comment by zenhack** [comment]
Hm, can we add a regression test for this? Maybe in tests/integration/keystone we should make sure we invoke the cli at least once.

Otherwise this looks fine.

**Comment by Izhmash** [comment]
@zenhack Would that be satisfied by calling `list_nodes all` and making sure the output matches what's expected?

**Comment by zenhack** [comment]
@Izhmash, yeah that should work.

**Comment by knikolla** [comment]
This looks good to me, agree on the requirement for integration testing.

In a follow-up improvement, we can avoid having to set the hil endpoint env variable in the case of keystone by registering hil in the service catalog and retrieving the endpoint url from the service catalog.

**Comment by zenhack** [comment]
Assuming travis passes, +1

**Pull request merged**
