### PR TITLE
Enable the passing of GET arguments from the cli

### PR DESCRIPTION
**Pull request by henn**
This was needed for #554

### CODE REVIEW

**Comment by henn** [comment]
This was needed for #554

**Comment by shwsun** [comment]
I am just about to ask why those ``return`` are missing and it is fixed. That's good!  Another question is: I dont think ``request`` has this ``param``, and what will be the difference between ``data`` and ``param``?

**Comment by henn** [comment]
>  Another question is: I dont think request has this param, and what will be the difference between data and param?
[param](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls) allows you to pass GET parameters, like what you see after the question mark in `http://foo.com/bar?param1=1`.

[data](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests) passes parameters via the body. This is valid for the `PUT` and `POST` methods, but is not standard for `GET`, which uses URL parameters.

**Comment by gsilvis** [comment]
Looks good to me.  +1

**Comment by zenhack** [comment]
-1. This breaks keystone; the HTTPClient class doesn't expect a params argument. The implementations for basic/no authentication will accept it because they're just request.Session, but KeystoneHTTPClient should throw a type error.

The good news is I think the underlying keystone session *does* support this, and I'm fine with updating our docs and passing that argument through, but if that's the approach we take you need to actually do that.

**Comment by gsilvis** [comment]
Oh, good point.  Can we also get a test of this functionality, to be run under both keystone and plain auth?

**Comment by zenhack** [comment]
@henn, you've got merge conflicts now as well (we *finally* merged #628).

**Comment by shwsun** [comment]
@zenhack Hi Ian, I guess I will be working on this PR for a while. 

Do you still think that we need some extra work, i.e. to let the HTTPClient class accept the param argument? If so, does it mean I will have to touch the keystone session and the design we have?

**Comment by zenhack** [comment]
@shwsun, yeah, HTTPClient and the keystone subclass will need to be updated to support a `params` argument. I *believe* they underlying keystone session object we're using supports the exact same parameters, so it should just be a matter of passing the parameter through and updating the docstrings for HTTPClient, but do check the openstack docs for this.

**Comment by henn** [comment]
Needs to support httpclient. Closing in favor of #655

**Pull request closed without merging**
