### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by naved001**
links to Install.rst and Hacking.rst have been fixed.

### CODE REVIEW

**Comment by shwsun** [comment]
This PR does not fix the problems. `HACKING.rst` and `UPGRADE.rst` no longer exist, and I would expect to change them to correct names.

**Comment by gsilvis** [comment]
Oh wow, I didn't realize how out of date that file was

**Comment by gsilvis** [comment]
In that case, the best course is probably to rewrite those sections entirely

**Comment by naved001** [comment]
@shwsun 
> Things like keystone doc should also be added.

You want to add [keystone-auth.md](https://github.com/CCI-MOC/hil/blob/master/docs/keystone-auth.md) to readme.rst?

**Pull request closed without merging**
